language: scala

scala:
- 2.11.1
- 2.9.2
- 2.9.1

jdk:
- openjdk7
- oraclejdk7
 
env:
- PLAY_VERSION=2.3.0
 
before_script:
- wget http://downloads.typesafe.com/typesafe-activator/1.2.10/typesafe-activator-1.2.10-minimal.zip
- unzip -q typesafe-activator-1.2.10-minimal.zip
- psql -c 'create database travis_ci_test;' -U postgres

script:
-  sbt test
 
notifications:
email: false

addons:
  postgresql: "9.1"

test:
  adapter: postgresql
  database: travis_ci_test
  username: postgres
