language: scala

scala:
- 2.11.1
- 2.9.2
- 2.9.1

jdk:
- openjdk7
- oraclejdk7
 
env:
- PLAY_VERSION=2.3.0

before_script:
- cp conf/travis.conf conf/application.conf
 
script: 
  sbt -Dconfig.file=conf/travis.conf test
 
